apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cnaas-front
  name: cnaas-front
spec:
  ports:
    - name: "4443"
      port: 4443
      targetPort: 80
  selector:
    io.kompose.service: cnaas-front
status:
  loadBalancer: {}
